services:
  - type: web
    name: faultai
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    pythonVersion: "3.11.0"
    envVars:
      - key: API_KEY
        sync: false